
### Solutions des exercices de programmation

::: {.callout-tip icon="false"}
## Solution 1 : Le drapeau national
**Explication :** Il faut diviser la largeur (300) par 3, puis utiliser le *slicing* de NumPy pour colorer toutes les lignes (`:`) d'un intervalle de colonnes précis.
* Noir : BGR [0, 0, 0] (déjà appliqué par `np.zeros`)
* Jaune : BGR [0, 255, 255]
* Rouge : BGR [0, 0, 255]

```python
import numpy as np
import cv2

h, w = 300, 300
drapeau = np.zeros((h, w, 3), dtype=np.uint8)
tiers = w // 3

# Bande 2 : Jaune (de 100 à 200)
drapeau[:, tiers:2*tiers] = [0, 255, 255]

# Bande 3 : Rouge (de 200 à 300)
drapeau[:, 2*tiers:w] = [0, 0, 255]

cv2.imwrite('drapeau.png', drapeau)
```

::: {.callout-tip icon="false"}

## Solution 2 : Les 4 quadrants
Explication : L'opérateur // permet de s'assurer que la division renvoie un nombre entier, ce qui est obligatoire pour manipuler les indices d'une matrice.

Python
import numpy as np
import cv2

h, w = 400, 400
image = np.zeros((h, w, 3), dtype=np.uint8)
mi_h = h // 2
mi_w = w // 2

image[0:mi_h, 0:mi_w] = [255, 0, 0]         # Haut-Gauche (Bleu BGR)
image[0:mi_h, mi_w:w] = [0, 255, 0]         # Haut-Droite (Vert BGR)
image[mi_h:h, 0:mi_w] = [0, 0, 255]         # Bas-Gauche (Rouge BGR)
image[mi_h:h, mi_w:w] = [255, 255, 255]     # Bas-Droite (Blanc BGR)

cv2.imwrite('quadrants.png', image)
:::

::: {.callout-tip icon="false"}

Solution 3 : Le cadre coloré
Explication : L'ordre des opérations est fondamental. Il est beaucoup plus efficace informatiquement de "peindre" toute l'image en bleu (le fond), puis de repeindre un rectangle jaune plus petit par-dessus.

Python
import numpy as np
import cv2

h, w = 500, 500
epaisseur = 20

# 1. On peint toute l'image en Bleu (future bordure)
image = np.zeros((h, w, 3), dtype=np.uint8)
image[:, :] = [255, 0, 0]

# 2. On peint l'intérieur en Jaune (on ignore les 20 premiers et derniers pixels)
image[epaisseur:h-epaisseur, epaisseur:w-epaisseur] = [0, 255, 255]

cv2.imwrite('cadre_jaune.png', image)
:::

::: {.callout-tip icon="false"}

Solution 4 : Le dégradé linéaire
Explication : En Python, faire une boucle for sur chaque pixel serait extrêmement lent. La force de NumPy est le broadcasting. Nous créons une simple ligne de 256 valeurs allant de 0 à 255 avec np.linspace (ou np.arange). En l'assignant au canal Rouge (image[:, :, 2]), NumPy comprend tout seul qu'il doit dupliquer cette ligne sur toute la hauteur de l'image !

Python
import numpy as np
import cv2

h, w = 256, 256
image = np.zeros((h, w, 3), dtype=np.uint8)

# Création d'un vecteur de 256 valeurs de 0 à 255
# astype(np.uint8) garantit le bon format pour l'image
degrade = np.linspace(0, 255, w).astype(np.uint8)

# Application du dégradé uniquement sur le canal Rouge (index 2 en BGR)
# ":" pour la hauteur, ":" pour la largeur, "2" pour le canal
image[:, :, 2] = degrade

cv2.imwrite('degrade_rouge.png', image)
:::

