<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Le codage des couleurs – Traitement d'Images</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_segmentation.html" rel="next">
<link href="./01_images_numeriques.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed7344add5f1663e434276306a2aa159.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_images_numeriques.html">I. Fondamentaux</a></li><li class="breadcrumb-item"><a href="./02_codage_couleurs.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Le codage des couleurs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Traitement d’Images</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Une introduction au traitement d’images</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I. Fondamentaux</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_images_numeriques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Images numériques</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_codage_couleurs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Le codage des couleurs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II. Traitements de Base</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Segmentation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III. Cas d’Utilisation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_use_cases_industrie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Use cases</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#le-codage-rgb-rvb" id="toc-le-codage-rgb-rvb" class="nav-link active" data-scroll-target="#le-codage-rgb-rvb"><span class="header-section-number">2.1</span> Le codage RGB (RVB)</a></li>
  <li><a href="#le-modèle-hsl-hue-saturation-luminance-ou-en-français-tsl-teinte-saturation-luminosité" id="toc-le-modèle-hsl-hue-saturation-luminance-ou-en-français-tsl-teinte-saturation-luminosité" class="nav-link" data-scroll-target="#le-modèle-hsl-hue-saturation-luminance-ou-en-français-tsl-teinte-saturation-luminosité"><span class="header-section-number">2.2</span> Le modèle HSL (Hue, Saturation, Luminance ou en français TSL : Teinte, Saturation, Luminosité)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_images_numeriques.html">I. Fondamentaux</a></li><li class="breadcrumb-item"><a href="./02_codage_couleurs.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Le codage des couleurs</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Le codage des couleurs</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="le-codage-rgb-rvb" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="le-codage-rgb-rvb"><span class="header-section-number">2.1</span> Le codage RGB (RVB)</h2>
<p>Nous avons vu qu’une couleur peut donc être définie par trois valeurs. Le système RVB repose sur une synthèse additive de 3 couleurs de base: le rouge, le vert et le bleu. On les appelle les trois composantes. Généralement, les valeurs de ces composantes sont comprises entre 0 et 255 (un octet). Il est donc possible de coder 16.777.216 couleurs différentes. Si chacune des composantes est à son maximum, le résultat est blanc ; si chacune est à son minimum, le résultat est noir (absence de lumière). Si nous avons la même proportion de rouge, de bleu et de vert, nous obtenons un niveau de gris. L’augmentation d’une composante accroît la luminosité du résultat.</p>
<div id="tbl-valeurs-rgb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-valeurs-rgb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Exemples de couleurs et leurs composantes RVB respectives
</figcaption>
<div aria-describedby="tbl-valeurs-rgb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Aperçu</th>
<th style="text-align: left;">Couleur</th>
<th style="text-align: center;">Rouge (R)</th>
<th style="text-align: center;">Vert (V)</th>
<th style="text-align: center;">Bleu (B)</th>
<th style="text-align: left;">Remarque</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(0,0,0); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Noir pur</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;">Absence totale de lumière (minimum)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(64,64,64); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Gris foncé</strong></td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">64</td>
<td style="text-align: left;">Les 3 valeurs sont égales et basses</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(128,128,128); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Gris moyen</strong></td>
<td style="text-align: center;">128</td>
<td style="text-align: center;">128</td>
<td style="text-align: center;">128</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(192,192,192); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Gris clair</strong></td>
<td style="text-align: center;">192</td>
<td style="text-align: center;">192</td>
<td style="text-align: center;">192</td>
<td style="text-align: left;">Les 3 valeurs sont égales et élevées</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(255,255,255); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Blanc pur</strong></td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">255</td>
<td style="text-align: left;">Addition maximale des 3 lumières</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(255,0,0); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge pur</strong></td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(100,0,0); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge foncé</strong></td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;">Baisse de la valeur R = baisse de luminosité</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(255,255,0); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Jaune pur</strong></td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;">Synthèse de Rouge + Vert</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(0,255,255); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Cyan pur</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">255</td>
<td style="text-align: left;">Synthèse de Vert + Bleu</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:rgb(255,0,255); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Magenta pur</strong></td>
<td style="text-align: center;">255</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">255</td>
<td style="text-align: left;">Synthèse de Rouge + Bleu</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Malheureusement, ce système de codage n’est pas très satisfaisant. Dans le domaine informatique, le codage RVB est dépendant du périphérique. Cela entraîne une dérive colorimétrique qui doit être corrigée par calibrage.</p>
<p>Cependant, le modèle RGB (Rouge, Vert, Bleu) est probablement le plus utilisé, mais comme nous allons le voir dans la suite, il n’est pas le seul.</p>
</section>
<section id="le-modèle-hsl-hue-saturation-luminance-ou-en-français-tsl-teinte-saturation-luminosité" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="le-modèle-hsl-hue-saturation-luminance-ou-en-français-tsl-teinte-saturation-luminosité"><span class="header-section-number">2.2</span> Le modèle HSL (Hue, Saturation, Luminance ou en français TSL : Teinte, Saturation, Luminosité)</h2>
<p>Le modèle HSL a été décrit par MUNSELL en 1905 et est plus proche de la manière dont un humain donne la description d’une couleur. En effet, si vous écoutez une quelqu’un décrire une couleur, on pourrait entendre : « Je cherche un bleu pastel très clair ». On retrouve dans cette phrase les notions fondamentales de teinte (bleu), de saturation (pastel) et de luminosité (très clair).</p>
<p>Notre cerveau agit donc comme un intégrateur qui détecte trois grandeurs physiques distinctes : * <strong>La teinte (Hue) :</strong> caractérisée par la longueur d’onde dominante du rayonnement (± 250 teintes monochromatiques détectables par l’œil, plus les pourpres). * <strong>La luminosité ou clarté (Lightness) :</strong> l’énergie lumineuse reçue (± 1000 niveaux de luminosité différents, selon la teinte). * <strong>La saturation (Saturation ou pureté de la couleur) :</strong> contribue à l’intensité de l’ensemble et permet de différencier une couleur vive d’une couleur pastel (atténuée) (± 20 000 différenciations).</p>
<p>Une couleur pure (un rouge flamboyant) sera donc saturée à 100 % et quand la saturation atteint 0%, il n’y a plus de dominante de couleur. La couleur est dite achromatique (absence de couleur) et révèle une nuance de gris, allant du blanc au noir selon la luminosité.</p>
<div id="tbl-valeurs-hsl" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-valeurs-hsl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Exemples de couleurs et leurs composantes TSL/HSL respectives
</figcaption>
<div aria-describedby="tbl-valeurs-hsl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Aperçu</th>
<th style="text-align: left;">Couleur</th>
<th style="text-align: center;">Teinte (H)</th>
<th style="text-align: center;">Saturation (S)</th>
<th style="text-align: center;">Luminosité (L)</th>
<th style="text-align: left;">Remarque</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,0%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Noir pur</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: left;">Luminosité à 0 = noir total, peu importe H et S</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,50%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Gris moyen</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">50%</td>
<td style="text-align: left;">Saturation à 0 = absence de pigment (nuance de gris)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,100%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Blanc pur</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">100%</td>
<td style="text-align: left;">Luminosité à 100 = blanc pur, peu importe H et S</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,50%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge pur</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">50%</td>
<td style="text-align: left;">Couleur fondamentale (0° = début du cercle chromatique)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,25%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge foncé</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">25%</td>
<td style="text-align: left;">On baisse L : on assombrit la même couleur</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,75%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge clair</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">75%</td>
<td style="text-align: left;">On monte L : on éclaircit la même couleur</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(0,30%,50%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Rouge délavé</strong></td>
<td style="text-align: center;">0°</td>
<td style="text-align: center;">30%</td>
<td style="text-align: center;">50%</td>
<td style="text-align: left;">On baisse S : la couleur devient fade (tend vers le gris)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(120,100%,50%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Vert pur</strong></td>
<td style="text-align: center;">120°</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">50%</td>
<td style="text-align: left;">Décalage d’un tiers (120°) sur le cercle chromatique</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="display:inline-block; width:18px; height:18px; background-color:hsl(240,100%,50%); border:1px solid #777; border-radius:3px;"></span></td>
<td style="text-align: left;"><strong>Bleu pur</strong></td>
<td style="text-align: center;">240°</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">50%</td>
<td style="text-align: left;">Décalage de deux tiers (240°) sur le cercle chromatique</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Vous remarquerez la teinte n’est pas donnée par une valeur entre 0 et 255 mais bien entre 0 et 360. H est donné en degré car elle est souvent réprésentée sur un cercle qui se transforme en cylindre avec la saturation et la luminance.</p>
<div id="fig-cylindre-hsl" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cylindre-hsl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images_dans_le_cours/HSL.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cylindre-hsl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Représentation en cylindre de l’espace colorimétrique HSL. La Teinte (Hue) correspond à l’angle, la Saturation correspond au rayon, et la Luminosité (Lightness) correspond à l’axe vertical.
</figcaption>
</figure>
</div>
<p>Comme on peut l’observer sur la <a href="#fig-cylindre-hsl" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> : - <strong>La Teinte (H)</strong> tourne autour de l’axe central (de 0° à 360°). - <strong>La Saturation (S)</strong> part de l’axe central gris (0%) vers le bord coloré du cylindre (100%). - <strong>La Luminosité (L)</strong> monte de la base noire (0%) vers le sommet blanc (100%).</p>
<section id="conversion-mathématique-entre-rvb-et-tsl-hsl" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="conversion-mathématique-entre-rvb-et-tsl-hsl"><span class="header-section-number">2.2.1</span> Conversion Mathématique entre RVB et TSL (HSL)</h3>
<p>Pour passer d’un espace colorimétrique à l’autre, les algorithmes (comme ceux intégrés dans OpenCV) utilisent une série d’opérations non linéaires.</p>
<p>Pour réaliser une conversion de RVB vers TSL (HSL) :</p>
<p>La première étape consiste toujours à <strong>normaliser</strong> les valeurs RVB de l’intervalle <span class="math inline">\([0, 255]\)</span> vers l’intervalle <span class="math inline">\([0, 1]\)</span>. On note ces valeurs normalisées <span class="math inline">\(R', G', B'\)</span>.</p>
<p>On cherche ensuite la composante maximale (<span class="math inline">\(C_{max}\)</span>), la composante minimale (<span class="math inline">\(C_{min}\)</span>) et la différence entre les deux (<span class="math inline">\(\Delta\)</span>).</p>
<p><span class="math display">\[
\begin{aligned}
C_{max} &amp;= \max(R', G', B') \\
C_{min} &amp;= \min(R', G', B') \\
\Delta &amp;= C_{max} - C_{min}
\end{aligned}
\]</span></p>
<p><strong>Calcul de la Luminosité (L) :</strong> La luminosité est simplement la moyenne entre la composante la plus forte et la plus faible. <span class="math display">\[ L = \frac{C_{max} + C_{min}}{2} \]</span></p>
<p><strong>Calcul de la Saturation (S) :</strong> Si <span class="math inline">\(\Delta = 0\)</span> (c’est-à-dire que <span class="math inline">\(R=G=B\)</span>), la couleur est une nuance de gris, donc la saturation est nulle. <span class="math display">\[
S = \begin{cases}
0 &amp; \text{si } \Delta = 0 \\
\frac{\Delta}{1 - |2L - 1|} &amp; \text{sinon}
\end{cases}
\]</span></p>
<p><strong>Calcul de la Teinte (H) :</strong> La teinte est calculée selon le secteur du cercle chromatique (par tranches de 60°) dominé par la couleur principale. <span class="math display">\[
H = \begin{cases}
0^\circ &amp; \text{si } \Delta = 0 \\
60^\circ \times \left( \frac{G' - B'}{\Delta} \bmod 6 \right) &amp; \text{si } C_{max} = R' \\
60^\circ \times \left( \frac{B' - R'}{\Delta} + 2 \right) &amp; \text{si } C_{max} = G' \\
60^\circ \times \left( \frac{R' - G'}{\Delta} + 4 \right) &amp; \text{si } C_{max} = B'
\end{cases}
\]</span> <em>(Si <span class="math inline">\(H &lt; 0^\circ\)</span>, on lui ajoute <span class="math inline">\(360^\circ\)</span> pour obtenir un angle positif).</em></p>
<hr>
<p>Pour la conversion inverse de TSL (HSL) vers RVB :</p>
<p>On utilise la Teinte (<span class="math inline">\(H \in [0, 360[\)</span>), la Saturation (<span class="math inline">\(S \in [0, 1]\)</span>) et la Luminosité (<span class="math inline">\(L \in [0, 1]\)</span>) pour retrouver <span class="math inline">\(R, G, B\)</span>.</p>
<p>On calcule d’abord les paramètres intermédiaires suivants (le Chroma <span class="math inline">\(C\)</span>, un paramètre <span class="math inline">\(X\)</span> et un ajustement de luminosité <span class="math inline">\(m\)</span>) : <span class="math display">\[
\begin{aligned}
C &amp;= (1 - |2L - 1|) \times S \\
X &amp;= C \times \left(1 - \left| \left(\frac{H}{60^\circ}\right) \bmod 2 - 1 \right|\right) \\
m &amp;= L - \frac{C}{2}
\end{aligned}
\]</span></p>
<p>On détermine ensuite les valeurs RVB temporaires <span class="math inline">\((R', G', B')\)</span> en fonction de l’angle de la Teinte <span class="math inline">\(H\)</span> : <span class="math display">\[
(R', G', B') = \begin{cases}
(C, X, 0) &amp; \text{si } 0^\circ \le H &lt; 60^\circ \\
(X, C, 0) &amp; \text{si } 60^\circ \le H &lt; 120^\circ \\
(0, C, X) &amp; \text{si } 120^\circ \le H &lt; 180^\circ \\
(0, X, C) &amp; \text{si } 180^\circ \le H &lt; 240^\circ \\
(X, 0, C) &amp; \text{si } 240^\circ \le H &lt; 300^\circ \\
(C, 0, X) &amp; \text{si } 300^\circ \le H &lt; 360^\circ
\end{cases}
\]</span></p>
<p>Enfin, on ajoute l’ajustement de luminosité <span class="math inline">\(m\)</span> et on dé-normalise pour retrouver les valeurs classiques sur un octet (0 à 255) : <span class="math display">\[
\begin{aligned}
R &amp;= (R' + m) \times 255 \\
G &amp;= (G' + m) \times 255 \\
B &amp;= (B' + m) \times 255
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Question de réflexion : La non-linéarité du modèle">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question de réflexion : La non-linéarité du modèle
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Pourquoi la transformation RVB <span class="math inline">\(\rightarrow\)</span> TSL est-elle non linéaire, et quelles en sont les implications concrètes en traitement d’images industriel ?</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Voir la réponse et l’explication
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Pourquoi est-ce non linéaire ?</strong> Contrairement au passage en niveaux de gris qui est une simple combinaison linéaire (une multiplication matricielle), la conversion vers le TSL utilise des opérations conditionnelles (fonctions <span class="math inline">\(\max\)</span> et <span class="math inline">\(\min\)</span>), des valeurs absolues et des divisions. Géométriquement, l’algorithme “déforme” un cube (l’espace RVB) pour l’enrouler et le faire rentrer dans un cylindre. Cette torsion mathématique a pour but de s’aligner sur la perception visuelle de l’œil humain, qui est elle-même fortement non linéaire.</p>
<p><strong>2. Les implications sur le terrain (vision industrielle) :</strong> Cette non-linéarité a trois conséquences majeures à prendre en compte lors du développement de vos algorithmes de contrôle qualité :</p>
<ul>
<li><strong>L’instabilité de la Teinte (Singularités) :</strong> Lorsque la saturation est très faible (sur des objets gris/métalliques) ou que l’image est très sombre/très surexposée, la différence <span class="math inline">\(\Delta\)</span> s’approche de <span class="math inline">\(0\)</span>. Une infime variation de lumière ou un bruit de capteur (même de 1 bit sur un pixel) va faire bondir l’angle de la Teinte de manière chaotique. <em><span class="math inline">\(\rightarrow\)</span> Règle d’or : ne jamais baser une segmentation sur la Teinte si la Saturation ou la Luminosité sont trop faibles.</em></li>
<li><strong>Le problème de la circularité (Mathématique modulo) :</strong> La Teinte est un angle. Les valeurs <span class="math inline">\(0^\circ\)</span> (rouge) et <span class="math inline">\(359^\circ\)</span> (rouge) sont visuellement identiques mais numériquement opposées. Vous ne pouvez donc pas utiliser de simples moyennes mathématiques ou de distances euclidiennes sur la Teinte. (Par exemple, dans OpenCV, isoler la couleur rouge requiert souvent de créer deux masques : de 0 à 10 et de 170 à 179, puis de les additionner).</li>
<li><strong>Le coût de calcul (CPU) :</strong> Les divisions, les modulos et les branchements conditionnels (<code>if</code>) demandent plus de cycles d’horloge au processeur qu’une simple addition matricielle. Sur des lignes de production à cadence très élevée (milliers de pièces par minute), convertir une image haute résolution de RVB à TSL coûte un temps de traitement précieux qu’il faut budgétiser.</li>
</ul>
</div>
</div>
</div>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01_images_numeriques.html" class="pagination-link" aria-label="Images numériques">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Images numériques</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_segmentation.html" class="pagination-link" aria-label="Segmentation">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Segmentation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Le codage des couleurs</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Le codage RGB (RVB)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Nous avons vu qu'une couleur peut donc être définie par trois valeurs. Le système RVB repose sur une synthèse additive de 3 couleurs de base: le rouge, le vert et le bleu. On les appelle les trois composantes. Généralement, les valeurs de ces composantes sont comprises entre 0 et 255 (un octet). Il est donc possible de coder 16.777.216 couleurs différentes.  Si chacune des composantes est à son maximum, le résultat est blanc ; si chacune est à son minimum, le résultat est noir (absence de lumière). Si nous avons la même proportion de rouge, de bleu et de vert, nous obtenons un niveau de gris. L'augmentation d'une composante accroît la luminosité du résultat.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Aperçu <span class="pp">|</span> Couleur <span class="pp">|</span> Rouge (R) <span class="pp">|</span> Vert (V) <span class="pp">|</span> Bleu (B) <span class="pp">|</span> Remarque <span class="pp">|</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="pp">| :---:</span> <span class="pp">| :---</span> <span class="pp">| :---:</span> <span class="pp">| :---:</span> <span class="pp">| :---:</span> <span class="pp">| :---</span> <span class="pp">|</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(0,0,0); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Noir pur** <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> Absence totale de lumière (minimum) <span class="pp">|</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(64,64,64); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Gris foncé** <span class="pp">|</span> 64 <span class="pp">|</span> 64 <span class="pp">|</span> 64 <span class="pp">|</span> Les 3 valeurs sont égales et basses <span class="pp">|</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(128,128,128); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Gris moyen** <span class="pp">|</span> 128 <span class="pp">|</span> 128 <span class="pp">|</span> 128 <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(192,192,192); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Gris clair** <span class="pp">|</span> 192 <span class="pp">|</span> 192 <span class="pp">|</span> 192 <span class="pp">|</span> Les 3 valeurs sont égales et élevées <span class="pp">|</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(255,255,255); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Blanc pur** <span class="pp">|</span> 255 <span class="pp">|</span> 255 <span class="pp">|</span> 255 <span class="pp">|</span> Addition maximale des 3 lumières <span class="pp">|</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(255,0,0); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge pur** <span class="pp">|</span> 255 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(100,0,0); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge foncé**<span class="pp">|</span> 100 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> Baisse de la valeur R = baisse de luminosité <span class="pp">|</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(255,255,0); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Jaune pur** <span class="pp">|</span> 255 <span class="pp">|</span> 255 <span class="pp">|</span> 0 <span class="pp">|</span> Synthèse de Rouge + Vert <span class="pp">|</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(0,255,255); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Cyan pur** <span class="pp">|</span> 0 <span class="pp">|</span> 255 <span class="pp">|</span> 255 <span class="pp">|</span> Synthèse de Vert + Bleu <span class="pp">|</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:rgb(255,0,255); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Magenta pur**<span class="pp">|</span> 255 <span class="pp">|</span> 0 <span class="pp">|</span> 255 <span class="pp">|</span> Synthèse de Rouge + Bleu <span class="pp">|</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>: Exemples de couleurs et leurs composantes RVB respectives {#tbl-valeurs-rgb}</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>Malheureusement, ce système de codage n'est pas très satisfaisant. Dans le domaine informatique, le codage RVB est dépendant du périphérique. Cela entraîne une dérive colorimétrique qui doit être corrigée par calibrage.</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>Cependant, le modèle RGB (Rouge, Vert, Bleu) est probablement le plus utilisé, mais comme nous allons le voir dans la suite, il n'est pas le seul.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## Le modèle HSL (Hue, Saturation, Luminance ou en français TSL : Teinte, Saturation, Luminosité)</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>Le modèle HSL a été décrit par MUNSELL en 1905 et est plus proche de la manière dont un humain donne la description d'une couleur. En effet, si vous écoutez une quelqu'un décrire une couleur, on pourrait entendre : « Je cherche un bleu pastel très clair ». On retrouve dans cette phrase les notions fondamentales de teinte (bleu), de saturation (pastel) et de luminosité (très clair).</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>Notre cerveau agit donc comme un intégrateur qui détecte trois grandeurs physiques distinctes :</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**La teinte (Hue) :** caractérisée par la longueur d'onde dominante du rayonnement (± 250 teintes monochromatiques détectables par l'œil, plus les pourpres).</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**La luminosité ou clarté (Lightness) :** l'énergie lumineuse reçue (± 1000 niveaux de luminosité différents, selon la teinte).</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**La saturation (Saturation ou pureté de la couleur) :** contribue à l'intensité de l'ensemble et permet de différencier une couleur vive d'une couleur pastel (atténuée) (± 20 000 différenciations).</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Une couleur pure (un rouge flamboyant) sera donc saturée à 100 % et quand la saturation atteint 0%, il n'y a plus de dominante de couleur. La couleur est dite achromatique (absence de couleur) et révèle une nuance de gris, allant du blanc au noir selon la luminosité.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Aperçu <span class="pp">|</span> Couleur <span class="pp">|</span> Teinte (H) <span class="pp">|</span> Saturation (S) <span class="pp">|</span> Luminosité (L) <span class="pp">|</span> Remarque <span class="pp">|</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="pp">| :---:</span> <span class="pp">| :---</span> <span class="pp">| :---:</span> <span class="pp">| :---:</span> <span class="pp">| :---:</span> <span class="pp">| :---</span> <span class="pp">|</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,0%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Noir pur** <span class="pp">|</span> 0° <span class="pp">|</span> 0% <span class="pp">|</span> 0% <span class="pp">|</span> Luminosité à 0 = noir total, peu importe H et S <span class="pp">|</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,50%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Gris moyen** <span class="pp">|</span> 0° <span class="pp">|</span> 0% <span class="pp">|</span> 50% <span class="pp">|</span> Saturation à 0 = absence de pigment (nuance de gris) <span class="pp">|</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,0%,100%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Blanc pur** <span class="pp">|</span> 0° <span class="pp">|</span> 0% <span class="pp">|</span> 100% <span class="pp">|</span> Luminosité à 100 = blanc pur, peu importe H et S <span class="pp">|</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,50%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge pur** <span class="pp">|</span> 0° <span class="pp">|</span> 100% <span class="pp">|</span> 50% <span class="pp">|</span> Couleur fondamentale (0° = début du cercle chromatique) <span class="pp">|</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,25%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge foncé**<span class="pp">|</span> 0° <span class="pp">|</span> 100% <span class="pp">|</span> 25% <span class="pp">|</span> On baisse L : on assombrit la même couleur <span class="pp">|</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,100%,75%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge clair**<span class="pp">|</span> 0° <span class="pp">|</span> 100% <span class="pp">|</span> 75% <span class="pp">|</span> On monte L : on éclaircit la même couleur <span class="pp">|</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(0,30%,50%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Rouge délavé**<span class="pp">|</span> 0° <span class="pp">|</span> 30% <span class="pp">|</span> 50% <span class="pp">|</span> On baisse S : la couleur devient fade (tend vers le gris) <span class="pp">|</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(120,100%,50%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Vert pur** <span class="pp">|</span> 120° <span class="pp">|</span> 100% <span class="pp">|</span> 50% <span class="pp">|</span> Décalage d'un tiers (120°) sur le cercle chromatique <span class="pp">|</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="dt">&lt;</span><span class="kw">span</span><span class="ot"> style</span><span class="op">=</span><span class="st">"display:inline-block; width:18px; height:18px; background-color:hsl(240,100%,50%); border:1px solid #777; border-radius:3px;"</span><span class="dt">&gt;&lt;/</span><span class="kw">span</span><span class="dt">&gt;</span> <span class="pp">|</span> **Bleu pur** <span class="pp">|</span> 240° <span class="pp">|</span> 100% <span class="pp">|</span> 50% <span class="pp">|</span> Décalage de deux tiers (240°) sur le cercle chromatique <span class="pp">|</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>: Exemples de couleurs et leurs composantes TSL/HSL respectives {#tbl-valeurs-hsl}</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>Vous remarquerez la teinte n'est pas donnée par une valeur entre 0 et 255 mais bien entre 0 et 360. H est donné en degré car elle est souvent réprésentée sur un cercle qui se transforme en cylindre avec la saturation et la luminance.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="al">![Représentation en cylindre de l'espace colorimétrique HSL. La Teinte (Hue) correspond à l'angle, la Saturation correspond au rayon, et la Luminosité (Lightness) correspond à l'axe vertical.](images_dans_le_cours/HSL.png)</span>{#fig-cylindre-hsl}</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Comme on peut l'observer sur la @fig-cylindre-hsl :</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**La Teinte (H)** tourne autour de l'axe central (de 0° à 360°).</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**La Saturation (S)** part de l'axe central gris (0%) vers le bord coloré du cylindre (100%).</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**La Luminosité (L)** monte de la base noire (0%) vers le sommet blanc (100%).</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conversion Mathématique entre RVB et TSL (HSL)</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Pour passer d'un espace colorimétrique à l'autre, les algorithmes (comme ceux intégrés dans OpenCV) utilisent une série d'opérations non linéaires. </span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>Pour réaliser une conversion de RVB vers TSL (HSL) :</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>La première étape consiste toujours à **normaliser** les valeurs RVB de l'intervalle $<span class="co">[</span><span class="ot">0, 255</span><span class="co">]</span>$ vers l'intervalle $<span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$. On note ces valeurs normalisées $R', G', B'$.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>On cherche ensuite la composante maximale ($C_{max}$), la composante minimale ($C_{min}$) et la différence entre les deux ($\Delta$).</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>C_{max} &amp;= \max(R', G', B') <span class="sc">\\</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>C_{min} &amp;= \min(R', G', B') <span class="sc">\\</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>\Delta &amp;= C_{max} - C_{min}</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>**Calcul de la Luminosité (L) :**</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>La luminosité est simplement la moyenne entre la composante la plus forte et la plus faible.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>$$ L = \frac{C_{max} + C_{min}}{2} $$</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>**Calcul de la Saturation (S) :**</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>Si $\Delta = 0$ (c'est-à-dire que $R=G=B$), la couleur est une nuance de gris, donc la saturation est nulle.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>S = \begin{cases} </span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>0 &amp; \text{si } \Delta = 0 <span class="sc">\\</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>\frac{\Delta}{1 - |2L - 1|} &amp; \text{sinon}</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>\end{cases}</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>**Calcul de la Teinte (H) :**</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>La teinte est calculée selon le secteur du cercle chromatique (par tranches de 60°) dominé par la couleur principale.</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>H = \begin{cases} </span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>0^\circ &amp; \text{si } \Delta = 0 <span class="sc">\\</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>60^\circ \times \left( \frac{G' - B'}{\Delta} \bmod 6 \right) &amp; \text{si } C_{max} = R' <span class="sc">\\</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>60^\circ \times \left( \frac{B' - R'}{\Delta} + 2 \right) &amp; \text{si } C_{max} = G' <span class="sc">\\</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>60^\circ \times \left( \frac{R' - G'}{\Delta} + 4 \right) &amp; \text{si } C_{max} = B'</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>\end{cases}</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>*(Si $H &lt; 0^\circ$, on lui ajoute $360^\circ$ pour obtenir un angle positif).*</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Pour la conversion inverse de TSL (HSL) vers RVB :</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>On utilise la Teinte ($H \in <span class="co">[</span><span class="ot">0, 360[$), la Saturation ($S \in [0, 1</span><span class="co">]</span>$) et la Luminosité ($L \in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$) pour retrouver $R, G, B$.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>On calcule d'abord les paramètres intermédiaires suivants (le Chroma $C$, un paramètre $X$ et un ajustement de luminosité $m$) :</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>C &amp;= (1 - |2L - 1|) \times S <span class="sc">\\</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>X &amp;= C \times \left(1 - \left| \left(\frac{H}{60^\circ}\right) \bmod 2 - 1 \right|\right) <span class="sc">\\</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>m &amp;= L - \frac{C}{2}</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>On détermine ensuite les valeurs RVB temporaires $(R', G', B')$ en fonction de l'angle de la Teinte $H$ :</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>(R', G', B') = \begin{cases} </span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>(C, X, 0) &amp; \text{si } 0^\circ \le H &lt; 60^\circ <span class="sc">\\</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>(X, C, 0) &amp; \text{si } 60^\circ \le H &lt; 120^\circ <span class="sc">\\</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>(0, C, X) &amp; \text{si } 120^\circ \le H &lt; 180^\circ <span class="sc">\\</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>(0, X, C) &amp; \text{si } 180^\circ \le H &lt; 240^\circ <span class="sc">\\</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>(X, 0, C) &amp; \text{si } 240^\circ \le H &lt; 300^\circ <span class="sc">\\</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>(C, 0, X) &amp; \text{si } 300^\circ \le H &lt; 360^\circ </span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>\end{cases}</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>Enfin, on ajoute l'ajustement de luminosité $m$ et on dé-normalise pour retrouver les valeurs classiques sur un octet (0 à 255) :</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>R &amp;= (R' + m) \times 255 <span class="sc">\\</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>G &amp;= (G' + m) \times 255 <span class="sc">\\</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>B &amp;= (B' + m) \times 255</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Question de réflexion : La non-linéarité du modèle"}</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>**Pourquoi la transformation RVB $\rightarrow$ TSL est-elle non linéaire, et quelles en sont les implications concrètes en traitement d'images industriel ?**</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="fu">### Voir la réponse et l'explication</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>**1. Pourquoi est-ce non linéaire ?**</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>Contrairement au passage en niveaux de gris qui est une simple combinaison linéaire (une multiplication matricielle), la conversion vers le TSL utilise des opérations conditionnelles (fonctions $\max$ et $\min$), des valeurs absolues et des divisions. Géométriquement, l'algorithme "déforme" un cube (l'espace RVB) pour l'enrouler et le faire rentrer dans un cylindre. Cette torsion mathématique a pour but de s'aligner sur la perception visuelle de l'œil humain, qui est elle-même fortement non linéaire.</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>**2. Les implications sur le terrain (vision industrielle) :**</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>Cette non-linéarité a trois conséquences majeures à prendre en compte lors du développement de vos algorithmes de contrôle qualité :</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**L'instabilité de la Teinte (Singularités) :** Lorsque la saturation est très faible (sur des objets gris/métalliques) ou que l'image est très sombre/très surexposée, la différence $\Delta$ s'approche de $0$. Une infime variation de lumière ou un bruit de capteur (même de 1 bit sur un pixel) va faire bondir l'angle de la Teinte de manière chaotique. </span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>*$\rightarrow$ Règle d'or : ne jamais baser une segmentation sur la Teinte si la Saturation ou la Luminosité sont trop faibles.*</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Le problème de la circularité (Mathématique modulo) :** La Teinte est un angle. Les valeurs $0^\circ$ (rouge) et $359^\circ$ (rouge) sont visuellement identiques mais numériquement opposées. Vous ne pouvez donc pas utiliser de simples moyennes mathématiques ou de distances euclidiennes sur la Teinte. (Par exemple, dans OpenCV, isoler la couleur rouge requiert souvent de créer deux masques : de 0 à 10 et de 170 à 179, puis de les additionner).</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Le coût de calcul (CPU) :** Les divisions, les modulos et les branchements conditionnels (<span class="in">`if`</span>) demandent plus de cycles d'horloge au processeur qu'une simple addition matricielle. Sur des lignes de production à cadence très élevée (milliers de pièces par minute), convertir une image haute résolution de RVB à TSL coûte un temps de traitement précieux qu'il faut budgétiser.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>