project:
  type: book
  output-dir: _book

book:
  title: "Traitement d'Images"
  subtitle: "Master 2 Informatique"
  author: "Rudi GIOT" # À modifier avec votre nom
  date: "Septembre 2026"
  
  # C'est ici que l'on définit l'ordre du menu de navigation à gauche
  chapters:
    - index.qmd
    - part: "I. Fondamentaux"
      chapters: 
        - 01_images_numeriques.qmd
        - 02_codage_couleurs.qmd
    - part: "II. Cas pratiques"
      chapters:
        - 03_segmentation.qmd
        - 04_use_cases_industrie.qmd

format:
  html:
    theme: cosmo        # Un thème sobre, très lisible et moderne
    css: style.css     # Ajout des styles perso
    toc: true           # Active la table des matières sur la droite
    toc-depth: 2        # Profondeur de la table des matières
    number-sections: true 
    code-fold: false    # Permet de masquer/afficher les longs blocs de code si on le passe à "true"
    code-tools: true    # Ajoute un bouton pour que les étudiants puissent copier le code
  
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
    colorlinks: true



